version: "3.9"  # optional since v1.27.0
services:
  db:
    build:
      context: ./docker
      dockerfile: pg.Dockerfile
    image: pg
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-passwd
    secrets:
      - postgres-passwd
    ports:
      - 3001:5432

  flask:
    build:
      context: .
      dockerfile: ./docker/flask.Dockerfile
    volumes:
      - ./src:/app/src
    expose:
      - 8080
    container_name: 'flask'

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx.Dockerfile
    volumes:
      - ./src:/app/src
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    container_name: 'nginx'
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  ##############################
  # Certbot Container
  ##############################
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  db-data:
secrets:
  postgres-passwd:
    file: ./secrets/postgres-passwd