version: "3.9"  # optional since v1.27.0
services:
  api:
    build:
      context: .
      dockerfile: ./docker/api.Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - 8080:80
    hostname: 'api'