version: "3.9"  # optional since v1.27.0
services:
  db:
    build:
      context: ./docker
      dockerfile: pg.Dockerfile
    image: pg
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-passwd
    secrets:
      - postgres-passwd
    ports:
      - 3001:5432

  flask:
    build:
      context: .
      dockerfile: ./docker/flask.Dockerfile
    volumes:
      - ./src:/app/src
    expose:
      - 8080
    container_name: 'flask'

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx.Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - "80:80"
    container_name: 'nginx'

volumes:
  db-data:
secrets:
  postgres-passwd:
    file: ./secrets/postgres-passwd