openapi: 3.0.0

servers:
  - url: http://localhost:8080/
    description: Local test server (docker compose)
  - url: http://localhost:8081/
    description: Local test server - running directly

info:
  description: Crowdfunding API
  version: "1.0.0"
  title: Crowdfunding API
  contact:
    email: santos.mateus@protonmail.com

paths:
  /health:
    get:
      summary: provides a health check for the application
      operationId: api.health.get
      description: |
        Gets the health of the application
      responses:
        "200":
          description: Successful health check - status will be 'ok' if health is good
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthStatus"
        "500":
          description: Unsuccessful health check

  /projects:
    get:
      summary: Returns a list of all projects
      operationId: api.projects.get_projects
      description: Returns short information about all projects paginated
      parameters:
        - in: query
          name: count
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 100
          description: The number of results displayed on one page.
        - in: query
          name: page
          schema:
            type: integer
            minimum: 1
            default: 1
          description: The page number for listing the results.
        - in: query
          name: order
          schema:
            type: string
            default: "desc"
            enum:
              - "asc"
              - "desc"
          description: The ordering of the items.
      responses:
        "200":
          description: Able to get all projects successfully
          content:
            application/json:
              schema:
                type: object
                required:
                  - projects
                  - count
                properties:
                  projects:
                    type: array
                    items:
                      $ref: "#/components/schemas/ProjectInfo"
                  count:
                    type: integer
                    example: 5

  /projects/create:
    post:
      summary: Creates a project
      operationId: api.projects.create_project
      description: |
        Creates a project with the specified parameters
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProjectCreateProps"
      responses:
        "200":
          description: |
            Whether everything went okay while trying to create the project
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: True
                  message:
                    type: string
                    example: "Something real bad happened"

  /projects/{project_id}:
    get:
      summary: Get details of a specific project
      operationId: api.projects.get_project
      description: Returns detailed information about a specific project
      parameters:
        - in: path
          name: project_id
          description: project id (guid)
          required: true
          schema:
            type: string
            example: "a7420038-3a6d-48e0-8960-cdf839e46f4e"
      responses:
        "200":
          description: Able to get the project successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: True
                  project:
                    $ref: "#/components/schemas/ProjectInfo"

        "404":
          description: Project ID not found

  /projects/{project_id}/{address}:
    get:
      summary: Get details of a specific project in relation to this user
      operationId: api.projects.get_project_user
      description: Returns detailed information about a specific project in relation to this user
      parameters:
        - in: path
          name: project_id
          description: project id (guid)
          required: true
          schema:
            type: string
            example: "a7420038-3a6d-48e0-8960-cdf839e46f4e"
        - in: path
          name: address
          description: address of the user whose relation with this project we want to get
          required: true
          schema:
            type: string
            example: "addr_test123"
      responses:
        "200":
          description: Able to get the project successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  funder:
                    type: boolean
                    example: True
                  creator:
                    type: boolean
                    example: False
                  mediator:
                    type: boolean
                    example: False

        "400":
          description: Something wrong happened (return message)

        "404":
          description: Project ID or User address not found

  /register/{address}:
    post:
      summary: Registers a user to the platform
      operationId: api.user.register
      description: Adds user to db if he provides a valid signature
      parameters:
        - in: path
          name: address
          description: the address of the user who is trying to register
          required: true
          schema:
            type: string
            example: "addr_test123"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - signature
              properties:
                email:
                  type: string
                  example: babatomano@email.com
                signature:
                  $ref: "#/components/schemas/Signature"
      responses:
        "200":
          description: |
            Whether everything went okay while trying to register user
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: True
                  message:
                    type: string
                    example: "Something real bad happened"

  /user/{address}:
    get:
      summary: Info about user
      operationId: api.user.get_info
      description: Get's information about user with this address
      parameters:
        - in: path
          name: address
          description: the address of the user who we are trying to get information from
          required: true
          schema:
            type: string
            example: "addr_test123"
      responses:
        "200":
          description: Whether everything went okay while trying to register user
          content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: string
                    example: babatomano@email.com
                  address:
                    type: string
                    example: addr_test123
                  nft_policy_identifier:
                    type: string
                    example: policy123
        "404":
          description: If we couldn't find a user with this address
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Sorry bro, couldn't find your address"

  /transaction/projects/fund:
    post:
      operationId: "api.transaction.fund_project"
      summary: "Get cbor from transaction to fund a project"
      description: "Get cbor from transaction to fund a project"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - registered_address
                - funding_utxos
                - funding_amount
                - project_id
              properties:
                registered_address:
                  type: string
                  example: addr_test123
                funding_utxos:
                  type: array
                  items:
                    type: string
                    example: cbor123
                funding_amount:
                  type: integer
                  example: 10_000_000
                project_id:
                  type: string
                  example: ba3fa9fd-79c8-4a78-b75d-893620de0e7b
      responses:
        200:
          description: "Successful entry will respond with {success:true}"
          content:
            application/json:
              schema:
                type: object
                properties:
                  transaction_cbor:
                    type: string
                    example: "cbor123"
                  witness_cbor:
                    type: string
                    example: "cbor123"
                  message:
                    type: string
                    example: "An error has ocurred"
                  

components:
  schemas:
    HealthStatus:
      type: object
      required:
        - status
      properties:
        status:
          type: boolean
          example: true
        message:
          type: string
          example: "Something really bad happened!"

    User:
      type: object
      required:
        - id
        - address
        - email
      properties:
        id:
          type: string
          example: 5e97a1ee-7ed2-4287-85cf-d3f8d566da0c
        address:
          type: string
          example: addr_test123
        email:
          type: string
          example: mateus@email.com

    Signature:
      oneOf:
        - type: object
          required:
            - signature
            - key
          properties:
            signature:
              type: string
              example: 84584d...db070c
              description: A signature from an arbitrary message the server sent to the user following CIP08
            key:
              type: string
              example: a40101...7dc780
              description: The key used to sign that message
        - type: string
          example: 84584d...db070c
          description: Another possible format that already includes signature and key in one string

    ProjectCreateProps:
      type: object
      required:
        - signature
        - name
        - short_description
        - long_description
        - creator
        - mediators
        - subjects
        - deliverables
        - days_to_complete
      properties:
        signature:
          $ref: "#/components/schemas/Signature"
        name:
          type: string
          example: "Who Done It 200+ Pages Book"
        creator:
          type: string
          example: addr_test123
        mediators:
          type: array
          items:
            type: string
            example: "mediator@email.com"
        short_description:
          type: string
          example: "I will write a story about a murder that happened in a spaceship! The ending will be incredible!"
        long_description:
          type: string
          example: "Loooong and boooooring description..."
        subjects:
          type: array
          items:
            type: string
            example: Math
        deliverables:
          type: array
          items:
            type: string
            example: "I am gonna do a very good job, trust me :wink"
        days_to_complete:
          type: integer
          example: 31

    ProjectInfo:
      type: object
      required:
        - project_id
        - name
        - creator
        - short_description
        - long_description
        - mediators
        - subjects
        - deliverables
        - days_to_complete
      properties:
        project_id:
          type: string
          example: "473ca642-d238-4b93-b7e4-424a76128727"
        name:
          type: string
          example: "Who Done It 200+ Pages Book"
        creator:
          $ref: "#/components/schemas/User"
        mediators:
          type: array
          items:
            $ref: "#/components/schemas/User"
        short_description:
          type: string
          example: "Short description..."
        long_description:
          type: string
          example: "Loooong and boooooring description..."
        subjects:
          type: array
          items:
            type: string
            example: Math
        reward_requested:
          type: integer
          example: 100
        days_to_complete:
          type: integer
          example: 31
        collateral:
          type: integer
          example: 200
        deliverables:
          type: array
          items:
            type: string
            example: "I am gonna do a very good job, trust me :wink"